;These are just the size and UI settings etc.
;Modify the colours by right clicking a swatch to swap
;or middle click to delete a swatch
;and click on the + to add a swatch
[Variables]
Height=40
Width=40
WidthIsLocked=1
Vertical=0

;UI COLOURS
BACKGROUND = 4d4d4d
SLIDERBACK = 79b7e2
LOCKBACK = ffbc45
TEXTBACK = ffd075
FontColor = ffffff
SLIDER = ffd075
GREEN = 9ab788
SEMIGREEN = 64827d
NEUTRAL = ccb1a6
RED = ea625c

;System Variables, DON'T TOUCH !!!
Unlock=0
;This makes the lock work don't touch thanks.
Horizontal=1
;This makes the orientation indicator work, don't touch thanks.
Refreshed=1
;This makes the whole damn skin work, don't touch thanks.
AlignVer=-1
AlignHor=0
;These two make the alignment system work don't, touch thanks.
TotalWidth=360
TotalHeight=40
;More alignment stuff, don't touch thanks.
AutoScale=0
;Fill/Tile mode variable, don't touch thanks.
CurrentTheme=Themes\Pastels.inc
;Theme select variable, don't touch thanks.
PlusScale=70
;The scale of the plus. #PlusScale# out of 100. No need to touch thanks.
