[Swatch3]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color E93595 | Strokewidth 0
X=0R
[Swatch4]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 9A18B0 | Strokewidth 0
X=0R
[Swatch5]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 5924B7 | Strokewidth 0
X=0R
[Swatch6]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 132BB5 | Strokewidth 0
X=0R
[Swatch7]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 2179F3 | Strokewidth 0
X=0R
[Swatch8]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 01D2ED | Strokewidth 0
X=0R
[Swatch9]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 079D94 | Strokewidth 0
X=0R
[Swatch10] 
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 17AF1D | Strokewidth 0
X=0R
[Swatch11] 
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color 9DDC0B | Strokewidth 0
X=0R
[Swatch12] 
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color FFEC40 | Strokewidth 0
X=0R
[Swatch13]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color FFB31A | Strokewidth 0
X=0R
[Swatch14]
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color FF6A01 | Strokewidth 0
X=R
[Swatch15] 
Meter=Shape
Shape=Rectangle 0,0,40,40 | Fill Color E70101 | Strokewidth 0
X=0R