[SponsoredTitle]
Meter=String
Text=Links
MeterStyle=TextStyle
FontColor=#FontColor#
X=(340 + (140/2))
Y=300
W=140
StringAlign=Center

[Github]
Meter=String
FontColor=#FontColor#
Text=[\xf09b]
FontFace=FontAwesome
FontSize=25
X=(340)
Y=350
H=37
W=40
Padding=0,3,0,0
SolidColor=#SLIDERBACK#
TooltipTitle=GitHub
ToolTipText=https://github.com/sceleri/swatchbar
LeftMouseUpAction="https://github.com/sceleri/swatchbar"


[Youbtube]
Meter=String
FontColor=#FontColor#
Text=[\xf167]
FontFace=FontAwesome
FontSize=23
X=10R
Y=0r
H=35
W=38
MeterStyle=TextStyle
Padding=2,5,0,0
SolidColor=#SLIDERBACK#
TooltipTitle=YouTube
ToolTipText=https://youtube.com/c/sceleri
LeftMouseUpAction="https://youtube.com/c/sceleri"
